// Converts the verified OHLCV CSV into a typed module the composition imports.
// Source rows: Yahoo Finance daily history (cross-checked against StockAnalysis.com), see research/RESEARCH.md.
import fs from 'node:fs';
const csv = fs.readFileSync(new URL('../src/data/mrna_daily.csv', import.meta.url), 'utf8').trim().split('\n');
const [, ...rows] = csv;
const bars = rows
  .map((r) => {
    const [date, open, high, low, close, volume] = r.split(',');
    return { date, open: +open, high: +high, low: +low, close: +close, volume: +volume };
  })
  .sort((a, b) => a.date.localeCompare(b.date));
const out = `// GENERATED by scripts/build-data.mjs from src/data/mrna_daily.csv - do not edit by hand.
export type Bar = {date: string; open: number; high: number; low: number; close: number; volume: number};
export const MRNA_DAILY: Bar[] = ${JSON.stringify(bars)};
`;
fs.writeFileSync(new URL('../src/data/mrna.generated.ts', import.meta.url), out);
console.log(`wrote ${bars.length} bars ${bars[0].date} .. ${bars.at(-1).date}`);
